### PR TITLE
ENTESB-4895 Switchyard application with two services based on a WSDL …

### PR DESCRIPTION
**Pull request by dvirgiln**
https://issues.jboss.org/browse/ENTESB-4895

### CODE REVIEW

**Comment by cunningt** [comment]
@dvirgiln : Can we get a unit test for this?

**Comment by dvirgiln** [comment]
yes tom. Gonna Include the test right now.

**Comment by cunningt** [comment]
ok to test

**Comment by cunningt** [comment]
ok to test

**Comment by cunningt** [comment]
Processed by Jenkins.

**Pull request closed without merging**
