### PR TITLE
Implementing wildfly core/security https://issues.jboss.org/browse/SWITCHYARD-2847

### PR DESCRIPTION
**Pull request by arielcarrera**
This code must be improved and tested. (I am working now on a quickstart demo project using Oauth(OpenId connect) and bearer token autentication).

Check the code, this trying to solve a problem with switchyard on Wildfly (jboss-web dependency is no longer valid on Wildfly 8).
Furthermore, it has an implementation using Keycloak security (openid bearer token authentication) on Wildfly.

The next week if i can will send you a demo project using keycloak security on wildfly.

Note: For Wildfly 9 or 10, needs to make a change on dependencies. It was developed using Wildfly 8.1.0.Final

### CODE REVIEW

**Comment by arielcarrera** [comment]
I've added a demo quickstart Project to it.

**Comment by igarashitm** [comment]
Hi @arielcarrera ,

Thank you for this big contribution! and sorry for the delayed response. It looks great and I'd like to ask you a couple of things to merge this:

1. Could you 'squash' the commits into one?
1. Could you try this with latest upstream master of SwitchYard & WildFly10?
1. Is policy-security-saml quickstart still working on EAP6 & WildFly10 with this change? wondering why CLI scripts are commented out in POM
1. Is there any other quickstart you've tried with your code? I'll test with all the security related quickstarts before merge this, but if you did any of them already then please let me know how it went.

**Comment by igarashitm** [comment]
One more thing, it looks the org.keycloak.keycloak-core is not a part of WildFly10 distribution so we can't depend on it unless it could be installed automatically in SwitchYard installation. Any ideas?

**Comment by arielcarrera** [comment]
Hi Tomohisa, i will try to respond all your answers:
1- I will try to split the source in two different commits/issues but you needs to consider that one issue depends of the other.
2- I have updated the code until 1st March and made some changes to work with Wildfly 10.0.0.Final
3- Before of this commit, the security in Wildfly (8,9 and 10) has not been working. The issue SWITCHYARD-2847 is about this problem (I reported the problem in the forum). The Jboss EAP uses a different core/security module and it has not been changed by me. My changes to work with keycloak's security only refers to Wildfly. I don't have a Jboss EAP to try it, sorry. I think that "policy-security-saml" is working after this but it needs to be tested again.
4- I just tried with "policy-security-saml" and my keycloak example.
5- Yes, you are right. I installed a keycloak module on Wildfly. I will try to create the assemblies into de distribution folder if I can.

**Comment by igarashitm** [comment]
Thank you for working on this actively!

You're right, the security bits has been broken when I updated the WildFly version to 10 due to the servlet engine replacement (catalina > undertow). Before that the CLI scripts are required for both of EAP and WildFly, so just commenting it out should be breaking setup/cleanup for the policy-security-saml quickstart when running on EAP.

Fixing that basic security bits is mandatory anyway, on the other hand the keycloak support is experimental and we need to keep it optional so people doesn't use keycloak won't be annoyed. That's why I thought we need to manage separate JIRA and pull request.

**Comment by igarashitm** [comment]
So, I'm sorry to be changing my word, but now I think it would be better to have a manual step to add keycloak module and make it pluggable by configuration rather than install it automatically so that the other SwitchYard user won't be affected. Still your policy-security-openid-connect demo would be great enough for the SwitchYard+keycloak users.

**Comment by arielcarrera** [comment]
Hi Tomohisa, sorry for the delay, I have been a little busy during last days... as soon as i have time i will commit the two pull requests that you wants.
Thanks.

**Comment by igarashitm** [comment]
Closing as this is out of date

**Pull request closed without merging**
