### PR TITLE
SWITCHYARD-2990: Add validation error to exchange context

### PR DESCRIPTION
**Pull request by martinweiler**

### CODE REVIEW

**Comment by igarashitm** [comment]
Hi @martinweiler ,

The ValidationFailureException introduced recently holds the original ValidationResult and the Validator instance which actually performed the validation.
https://github.com/jboss-switchyard/switchyard/blob/master/core/api/src/main/java/org/switchyard/validate/ValidationFailureException.java

So if you catch the ValidationFailureException in the composer you can access the raw data of the validation. Doesn't it help for your case?

**Comment by andriyv** [comment]
@igarashitm i don't see a reason to throw exception from custom validator, since we have ValidationResult API and ValidationHandler which should handle it.

@martinweiler it would be better to hold ValidationResult as whole, not just message. This way we can provide srtuctured information, like list of validation errors (e.g. via subclassing ValidationResult)

**Comment by martinweiler** [comment]
@andriyv - there is no need to throw an exception in the custom validator. If you call 

`BaseValidator.DefaultValidationResult(false, "Something wrong");` 

in the custom validator, then [ValidateHandler](https://github.com/jboss-switchyard/switchyard/blob/master/core/runtime/src/main/java/org/switchyard/handlers/ValidateHandler.java#L76) throws the `ValidationFailureException` containing the `ValidationResult`.


Would this work for you?

**Comment by igarashitm** [comment]
Right, that's the reason why ValidationFailureException has been introduced as a part of API, as in older version we were just throwing HandlerException which doesn't contain failure details for the validation.

**Comment by martinweiler** [comment]
@andriyv - thanks for confirming that the approach outlined by @igarashitm will be sufficient. 

This PR is therefore not needed, and I will close it now. Sorry for the noise.

**Pull request closed without merging**
