### PR TITLE
SWITCHYARD-2810 RESTEasy OutboundHandler to sendFault for checked exceptions

### PR DESCRIPTION
**Pull request by cunningt**
https://issues.jboss.org/browse/SWITCHYARD-2810

### CODE REVIEW

**Comment by cunningt** [comment]
@igarashitm This look okay?   The patch was contributed and I tested it and it looks okay, but I'd love a second pair of eyes on the ClientInvoker part.

**Comment by igarashitm** [comment]
+1

**Comment by cunningt** [comment]
ok to test

**Comment by cunningt** [comment]
ok to test

**Comment by cunningt** [comment]
ok to test

**Comment by cunningt** [comment]
Processed.

**Pull request closed without merging**
