### PR TITLE
ENTESB-4587 SY: Support property replacement in 'from' and 'to' camel…

### PR DESCRIPTION
**Pull request by dvirgiln**
https://issues.jboss.org/browse/ENTESB-4587

### CODE REVIEW

**Comment by igarashitm** [comment]
SwitchYard property resolver had been already integrated into camel Properties component. The "{{name.of.property}}" syntax in the route definition should be replaced with SwitchYard properties. See this example:
https://github.com/jboss-switchyard/switchyard/blob/master/components/camel/component/src/test/resources/org/switchyard/component/camel/deploy/impl-route.xml
https://github.com/jboss-switchyard/switchyard/blob/master/components/camel/component/src/test/resources/org/switchyard/component/camel/deploy/switchyard-activator-impl.xml

**Comment by dvirgiln** [comment]
Then, I imagine the jira can be marked as resolved and the PR can be closed

**Comment by cunningt** [comment]
+1

**Comment by cunningt** [comment]
ok to test

**Pull request merged**
