### PR TITLE
SWITCHYARD-2701 JMSPriority not mapped correctly by JMSContextMapper

### PR DESCRIPTION
**Pull request by igarashitm**

### CODE REVIEW

**Comment by igarashitm** [comment]
Hold on, I'll make same fix for JMSEndpoint on sending reply and update this PR.

**Comment by igarashitm** [comment]
OK now it's ready to go.

**Comment by cunningt** [comment]
ok to test

**Comment by cunningt** [comment]
ok to test

**Comment by cunningt** [comment]
ok to test

**Pull request merged**
