### PR TITLE
ENTESB-4596 SY: Property expansion for soap binding

### PR DESCRIPTION
**Pull request by dvirgiln**
https://issues.jboss.org/browse/ENTESB-4596

### CODE REVIEW

**Comment by cunningt** [comment]
@dvirgiln : Do you mind adding a test that demonstrates this?

**Comment by dvirgiln** [comment]
I've included a change in one quickstart, so customers can see this capability (sometimes the capabilities are not known by customers because they are not demostrated on quickstarts). 

Anyway I consider is good as well to include a junit test.

**Comment by dvirgiln** [comment]
I ve included a junit test and I checked the checkstyle.

**Comment by cunningt** [comment]
ok to test

**Comment by cunningt** [comment]
Processed and merged to product branch.

**Pull request closed without merging**
